"use strict";Object.defineProperty(exports,"__esModule",{value:true});var NOOP=exports.NOOP=0;var SOCKS_VERSION_V4=exports.SOCKS_VERSION_V4=4;var SOCKS_VERSION_V5=exports.SOCKS_VERSION_V5=5;var METHOD_NO_AUTH=exports.METHOD_NO_AUTH=0;var REQUEST_COMMAND_CONNECT=exports.REQUEST_COMMAND_CONNECT=1;var REQUEST_COMMAND_BIND=exports.REQUEST_COMMAND_BIND=2;var REQUEST_COMMAND_UDP=exports.REQUEST_COMMAND_UDP=3;var ATYP_V4=exports.ATYP_V4=1;var ATYP_DOMAIN=exports.ATYP_DOMAIN=3;var ATYP_V6=exports.ATYP_V6=4;var REPLY_GRANTED=exports.REPLY_GRANTED=90;// 90
var REPLY_SUCCEEDED=exports.REPLY_SUCCEEDED=0;// export const REPLY_FAILURE = 0x01;
// export const REPLY_NOT_ALLOWED = 0x02;
// export const REPLY_NETWORK_UNREACHABLE = 0x03;
// export const REPLY_HOST_UNREACHABLE = 0x04;
// export const REPLY_CONNECION_REFUSED = 0x05;
// export const REPLY_TTL_EXXPIRED = 0x06;
var REPLY_COMMAND_NOT_SUPPORTED=exports.REPLY_COMMAND_NOT_SUPPORTED=7;// export const REPLY_ADDRESS_TYPE_NOT_SUPPORTED = 0x08;
var REPLY_UNASSIGNED=exports.REPLY_UNASSIGNED=255;