'use strict';Object.defineProperty(exports,'__esModule',{value:true});var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if('value'in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor)}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor}}();var _crypto=require('crypto');var _crypto2=_interopRequireDefault(_crypto);var _constants=require('../../constants');var _interface=require('./interface');function _interopRequireDefault(obj){return obj&&obj.__esModule?obj:{default:obj}}function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError('Cannot call a class as a function')}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError('this hasn\'t been initialised - super() hasn\'t been called')}return call&&(typeof call==='object'||typeof call==='function')?call:self}function _inherits(subClass,superClass){if(typeof superClass!=='function'&&superClass!==null){throw new TypeError('Super expression must either be null or a function, not '+typeof superClass)}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass}var IV_LEN=16;// Handshake packet:
//
// +-------+----------------+
// |  IV   |    PAYLOAD     |
// +-------+----------------+ = packet(encrypted without IV)
// | Fixed |    Variable    |
// +-------+----------------+
//
// Following packets:
//
// +----------------+
// |    PAYLOAD     |
// +----------------+ (encrypted with IV)
// |    Variable    |
// +----------------+
//
var BasicProtocol=function(_IProtocol){_inherits(BasicProtocol,_IProtocol);function BasicProtocol(){var _ref;var _temp,_this,_ret;_classCallCheck(this,BasicProtocol);for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key]}return _ret=(_temp=(_this=_possibleConstructorReturn(this,(_ref=BasicProtocol.__proto__||Object.getPrototypeOf(BasicProtocol)).call.apply(_ref,[this].concat(args))),_this),_this._isHandshakeDone=false,_temp),_possibleConstructorReturn(_this,_ret)}_createClass(BasicProtocol,[{key:'forwardToServer',value:function forwardToServer(payload,next,notify){if(this._isHandshakeDone){return payload}else{var iv=_crypto2.default.randomBytes(IV_LEN);notify({type:_constants.CRYPTO_SET_IV_AFTER,payload:iv});this._isHandshakeDone=true;return Buffer.concat([iv,payload])}}},{key:'forwardToDst',value:function forwardToDst(packet,next,notify){if(this._isHandshakeDone){return packet}else{var iv=packet.slice(0,IV_LEN);notify({type:_constants.CRYPTO_SET_IV,payload:iv});this._isHandshakeDone=true;return packet.slice(IV_LEN)}}},{key:'backwardToClient',value:function backwardToClient(payload){return payload}},{key:'backwardToApplication',value:function backwardToApplication(packet){return packet}}]);return BasicProtocol}(_interface.IProtocol);exports.default=BasicProtocol;